[package]
name = "ghostshare-quickshare"
version = "0.2.0"
edition = "2021"
license = "GPL-3.0-only"

[lib]
crate-type = ["staticlib", "cdylib"]

[dependencies]
rqs_lib = { path = "../../vendor/rquickshare", default-features = false }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["rt-multi-thread", "sync", "time", "macros"] }

tracing-subscriber = { version = "0.3", features = ["env-filter"] }
directories = "6"

[features]
default = ["bluetooth"]
bluetooth = ["rqs_lib/experimental"]
